### ISSUE TITLE
ImportError: No module named 'cairocffi'

### ISSUE THREAD

**Issue by codelabsprodev** [mgiraldo/tenprintcover-py#1]
I ran pip install cairocffi in my virtual env

==> pip freeze
cairocffi==0.7.2
cffi==1.4.2
pycparser==2.14
wsgiref==0.1.2
(venv)

I am running the tenprintcover.py script

https://github.com/mgiraldo/tenprintcover-py

with the following arguments

==> python3 tenprintcover.py --author "Clive Barker" --title "Imagica" --cover barker-imagica.png

I am getting the following error 
==> python3 tenprintcover.py --author "Arunabh Das" --title "Sails JS" --cover sailsjs.png
Traceback (most recent call last):
File "tenprintcover.py", line 23, in 
import cairocffi as cairo
ImportError: No module named 'cairocffi'
(venv)

**Comment by jenstroeger** [comment]
What happens when you run Python directly from your virtual environment?

```
(venv) ./bin/python
>>> import cairocffi
>>>
```

Do you get that same error? The pip you ran, I assume, is the one from your virtual environment: `(venv) ./bin/pip`? Is there a `cairocffi` folder in your `(venv)/lib/python3.4/site-packages` folder?

The error you're getting indicates that the [cairocffi](https://github.com/SimonSapin/cairocffi) package isn't part of your installed virtual Python environment.

**Comment by jenstroeger** [comment]
Closing this for now, because there's no follow-up. Please reopen if this issue remains.
