### ISSUE TITLE
Investigate more complex visual patterns

### ISSUE THREAD

**Issue by jenstroeger** [mgiraldo/tenprintcover-py#9]
There’s an interesting talk on [Complex Geometry of Islamic Designs](http://ed.ted.com/lessons/the-complex-geometry-of-islamic-design-eric-broug) over at TED-ed, which looks like an inspiring source to look deeper into interesting pattern generation and tessellation. Just a thought… 🤓

(Related, a new game called [Engare](http://www.engare.design/).)

**Comment by mgiraldo** [comment]
this looks cool... the pattern in our generator is based on [Casey Reas' 10 Print project](http://reas.com/10_print/) so the simplicity stems from that... you might want to look at [another cover generator](https://github.com/mgiraldo/feedbooks-covers), also open source, i did that used some [more info](https://raw.githubusercontent.com/mgiraldo/feedbooks-covers/master/data/feedbooks.json) about each title: type, language, category. it is not “constrained” by the 10print concept... not sure how easy it is to port to Python since it uses some 3D transforms...

**Comment by jenstroeger** [comment]
@mgiraldo, the [feedbook-covers](https://github.com/mgiraldo/feedbooks-covers) project looks great! Certainly doable to write in Python, but it’s a matter of time which I currently don’t have to spare… I do like the idea of having multiple visuals for book covers though.

**Comment by mgiraldo** [comment]
yeah you could use different cover generators depending on the data about the book that you have

**Comment by mgiraldo** [comment]
closing for now
